# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neverapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
